name: "Content Report 📄"
description: Report an issue or possible bug.
labels: [
  "improve documentation"
]
body:
  - type: markdown
    attributes:
      value: "# Reminder: If reporting a minor correction (e.g. typo), feel free to submit a PR directly!"
  - type: input
    id: subject
    attributes:
      label: 📚 Subject area/topic
      description: Documentation area/topic (e.g. SSR, CMS guide, environment variables)
      placeholder: "..."
    validations:
      required: true
  - type: textarea
    id: page
    attributes:
      label: "📋 Page(s) affected (or suggested, for new content)"
      description: Please provide the URL of the page(s) affected (or suggested, for new content).
      placeholder: https://docs.astro.build/en/getting-started/
    validations:
        required: true
  - type: textarea
    id: generalDesc
    attributes:
      label: "📋 General description or bullet points (if proposing new content)"
      description: If you are proposing new content please provide a general description or bullet points about what should be added.
      placeholder: "..."
    validations:
        required: true
  - type: textarea
    id: incorrectContent
    attributes:
      label: "🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)"
      description: If you are reporting incorrect content or code samples please attach a reproduction in stackblitz.
      placeholder: "..."
    validations:
        required: true