name: Update Translation Status

on:
  # Run on every push to the given branches
  push:
    branches: [main]
  # Allow the workflow to be run manually
  workflow_dispatch:

permissions:
  issues: write

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Update Translation Status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Update Translation Status
        run: pnpm run github:translation-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.repository_owner == 'withastro' && 438 || 0 }}
